[package]
name = "mtgjson"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["v5"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68" }
strum_macros = { version = "0.22.0" }
